name: "Contribute List"
description: "Automation of contributors list in README.md"
inputs:
    imageSize: # id of input
        description: "Size of square images in the stack"
        required: false
        default: "100"
    readme_path:
        description: "Path of the readme file you want to update"
        default: "README.md"
        required: false
    columnsPerRow: # id of input
        description: "Number of columns in a row"
        required: false
        default: "6"
    collaborators: # id of input
        description: "Type of collaborators options: all/direct/outside"
        required: false
        default: "direct"
runs:
    using: "node12"
    main: "index.js"
branding:
    icon: "archive"
    color: "black"
